import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Head from "next/head";
import React from "react";
import Link from "next/link";
import { MdKeyboardArrowRight } from "react-icons/md";

const blog = () => {
  return (
    <>
      <Head>
        <title>Bob & Scott - Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Englebert&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Header className="pa fc2" />
      <section className="about-hero df bg5">
        <div className="about-hero-box wrapper df aie jcc fc1 mt32">
          <h2 className="about-he inner-page-heading fc5 ff2 fw5 tac mb24">
            Explore Our World
          </h2>
        </div>
      </section>
      <div className="breadcrum ptb24 h-center">
        <ul className="breadcrum-list fc2 df fs18">
          <li className="bredcrum-item">
            <Link href="/home" className="category-item ttu plr16 v-center">
              Home <MdKeyboardArrowRight className="ml8" />
            </Link>
          </li>
          <li className="bredcrum-item">Blog</li>
        </ul>
      </div>
      <section className="blog ptb72 bg5">
        <div className="blog-section ptb40 wrapper ptb40">
          <h2 className="blog-sec-heading heading tac ttu fc2">Blog</h2>
          <div className="blog-card-container df fww mt32">
            <div className="blog-cards mtb32 flx33">
              <div className="blog-card mlr16 ofh br4 bg1">
                <img
                  src="images/chair-1x1-01.webp"
                  alt="chair-1x1"
                  className="w100"
                />
                <div className="blog-content plr16 ptb32">
                  <h2 className="blog-box-heading fs20 fw6 mb16">
                    Lorem, ipsum dolor.
                  </h2>
                  <p className="blog-box-subtext lh24 mb24">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                    Maxime molestiae sunt reprehenderit distinctio. Modi, aut.
                  </p>
                  <Link
                    href="#"
                    className="homeintro-button brd2 br50 transit2 fc-h1 zi2 ofh aft pr ls1 ptb16 plr32"
                  >
                    View More
                  </Link>
                </div>
              </div>
            </div>
            <div className="blog-cards mtb32 flx33">
              <div className="blog-card mlr16 ofh br4 bg1">
                <img
                  src="images/bed-1x1-01.webp"
                  alt="bed-1x1"
                  className="w100"
                />
                <div className="blog-content plr16 ptb32">
                  <h2 className="blog-box-heading fs20 fw6 mb16">
                    Lorem, ipsum dolor.
                  </h2>
                  <p className="blog-box-subtext lh24 mb24">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                    Maxime molestiae sunt reprehenderit distinctio. Modi, aut.
                  </p>
                  <Link
                    href="#"
                    className="homeintro-button brd2 br50 transit2 fc-h1 zi2 ofh aft pr ls1 ptb16 plr32"
                  >
                    View More
                  </Link>
                </div>
              </div>
            </div>
            <div className="blog-cards mtb32 flx33">
              <div className="blog-card mlr16 ofh br4 bg1">
                <img
                  src="images/bedTable-1x1-01.webp"
                  alt="bedTable-1x1"
                  className="w100"
                />
                <div className="blog-content plr16 ptb32">
                  <h2 className="blog-box-heading fs20 fw6 mb16">
                    Lorem, ipsum dolor.
                  </h2>
                  <p className="blog-box-subtext lh24 mb24">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                    Maxime molestiae sunt reprehenderit distinctio. Modi, aut.
                  </p>
                  <Link
                    href="#"
                    className="homeintro-button brd2 br50 transit2 fc-h1 zi2 ofh aft pr ls1 ptb16 plr32"
                  >
                    View More
                  </Link>
                </div>
              </div>
            </div>
            <div className="blog-cards mtb32 flx33">
              <div className="blog-card mlr16 ofh br4 bg1">
                <img
                  src="images/wardrobe-1x1-01.webp"
                  alt="wardrobe-1x1"
                  className="w100"
                />
                <div className="blog-content plr16 ptb32">
                  <h2 className="blog-box-heading fs20 fw6 mb16">
                    Lorem, ipsum dolor.
                  </h2>
                  <p className="blog-box-subtext lh24 mb24">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                    Maxime molestiae sunt reprehenderit distinctio. Modi, aut.
                  </p>
                  <Link
                    href="#"
                    className="homeintro-button brd2 br50 transit2 fc-h1 zi2 ofh aft pr ls1 ptb16 plr32"
                  >
                    View More
                  </Link>
                </div>
              </div>
            </div>
            <div className="blog-cards mtb32 flx33">
              <div className="blog-card mlr16 ofh br4 bg1">
                <img src="images/1x1-03.webp" alt="1x1-img" className="w100" />
                <div className="blog-content plr16 ptb32">
                  <h2 className="blog-box-heading fs20 fw6 mb16">
                    Lorem, ipsum dolor.
                  </h2>
                  <p className="blog-box-subtext lh24 mb24">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                    Maxime molestiae sunt reprehenderit distinctio. Modi, aut.
                  </p>
                  <Link
                    href="#"
                    className="homeintro-button brd2 br50 transit2 fc-h1 zi2 ofh aft pr ls1 ptb16 plr32"
                  >
                    View More
                  </Link>
                </div>
              </div>
            </div>
            <div className="blog-cards mtb32 flx33">
              <div className="blog-card mlr16 ofh br4 bg1">
                <img src="images/1x1-06.webp" alt="1x1-img" className="w100" />
                <div className="blog-content plr16 ptb32">
                  <h2 className="blog-box-heading fs20 fw6 mb16">
                    Lorem, ipsum dolor.
                  </h2>
                  <p className="blog-box-subtext lh24 mb24">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                    Maxime molestiae sunt reprehenderit distinctio. Modi, aut.
                  </p>
                  <Link
                    href="#"
                    className="homeintro-button brd2 br50 transit2 fc-h1 zi2 ofh aft pr ls1 ptb16 plr32"
                  >
                    View More
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <Footer />
    </>
  );
};

export default blog;
