import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Head from "next/head";
import React from "react";
import Link from "next/link";
import Room from "@/components/Room";
import { MdKeyboardArrowRight } from "react-icons/md";

const collections = () => {
  return (
    <>
      <Head>
        <title>Bob & Scott</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Englebert&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Header className="pa fc2" />
      <section className="about-hero df bg5">
        <div className="about-hero-box wrapper df aie jcc fc1 mt32">
          <h2 className="about-he inner-page-heading fc5 ff2 fw5 tac mb24">
            Featured Items
          </h2>
        </div>
      </section>
      <div className="breadcrum ptb24 h-center">
        <ul className="breadcrum-list fc2 df fs18">
          <li className="bredcrum-item">
            <Link href="/home" className="category-item ttu plr16 v-center">
              Home <MdKeyboardArrowRight className="ml8" />
            </Link>
          </li>
          <li className="bredcrum-item">Collection</li>
        </ul>
      </div>
      <Room className="bg5" />

      <Footer />
    </>
  );
};

export default collections;
