import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Head from "next/head";
import React from "react";
import Link from "next/link";
import { MdKeyboardArrowRight } from "react-icons/md";

const contact = () => {
  return (
    <>
      <Head>
        <title>Bob & Scott - Contact Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Englebert&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Header className="fc2 bg5 pa" />
      <section className="about-hero df bg5">
        <div className="about-hero-box wrapper df aie jcc fc1 mt32">
          <h2 className="about-he inner-page-heading fc5 ff2 fw5 tac mb24">
            Contact Us
          </h2>
        </div>
      </section>
      <div className="breadcrum ptb24 h-center">
        <ul className="breadcrum-list fc2 df fs18">
          <li className="bredcrum-item">
            <Link href="/home" className="category-item ttu plr16 v-center">
              Home <MdKeyboardArrowRight className="ml8" />
            </Link>
          </li>
          <li className="bredcrum-item">Contact Us</li>
        </ul>
      </div>
      <section className="contact-us bg5">
        <div className="contact df fww wrapper aic">
          <div className="contact-detail flx50 fc2 plr32">
            <h2 className="contact-title fs32 mb16">Contact Information</h2>
            <p className=" contact-subheading lh30 fs18 mb24">
              Get to know us, including how you can contact us and how we keep
              your information secure.
            </p>
            <div className="office-address ptb12">
              <p className="address lh24 df">
                <svg
                  stroke="currentColor"
                  fill="currentColor"
                  stroke-width="0"
                  viewBox="0 0 512 512"
                  className="fc2 mr8 fs24"
                  height="1em"
                  width="1em"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path d="M460.6 147.3L353 256.9c-.8.8-.8 2 0 2.8l75.3 80.2c5.1 5.1 5.1 13.3 0 18.4-2.5 2.5-5.9 3.8-9.2 3.8s-6.7-1.3-9.2-3.8l-75-79.9c-.8-.8-2.1-.8-2.9 0L313.7 297c-15.3 15.5-35.6 24.1-57.4 24.2-22.1.1-43.1-9.2-58.6-24.9l-17.6-17.9c-.8-.8-2.1-.8-2.9 0l-75 79.9c-2.5 2.5-5.9 3.8-9.2 3.8s-6.7-1.3-9.2-3.8c-5.1-5.1-5.1-13.3 0-18.4l75.3-80.2c.7-.8.7-2 0-2.8L51.4 147.3c-1.3-1.3-3.4-.4-3.4 1.4V368c0 17.6 14.4 32 32 32h352c17.6 0 32-14.4 32-32V148.7c0-1.8-2.2-2.6-3.4-1.4z"></path>
                  <path d="M256 295.1c14.8 0 28.7-5.8 39.1-16.4L452 119c-5.5-4.4-12.3-7-19.8-7H79.9c-7.5 0-14.4 2.6-19.8 7L217 278.7c10.3 10.5 24.2 16.4 39 16.4z"></path>
                </svg>{" "}
                P.O. BOX 18184, <br />
                Sugar Land, TX 77496-8184
              </p>
            </div>
            <div className="office-address ptb12">
              <p className="address lh24 df">
                <svg
                  stroke="currentColor"
                  fill="currentColor"
                  stroke-width="0"
                  viewBox="0 0 24 24"
                  className="fc2 mr8 fs24"
                  height="1em"
                  width="1em"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path fill="none" d="M0 0h24v24H0z"></path>
                  <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10h5v-2h-5c-4.34 0-8-3.66-8-8s3.66-8 8-8 8 3.66 8 8v1.43c0 .79-.71 1.57-1.5 1.57s-1.5-.78-1.5-1.57V12c0-2.76-2.24-5-5-5s-5 2.24-5 5 2.24 5 5 5c1.38 0 2.64-.56 3.54-1.47.65.89 1.77 1.47 2.96 1.47 1.97 0 3.5-1.6 3.5-3.57V12c0-5.52-4.48-10-10-10zm0 13c-1.66 0-3-1.34-3-3s1.34-3 3-3 3 1.34 3 3-1.34 3-3 3z"></path>
                </svg>
                bobscott@gmail.com
              </p>
            </div>
          </div>
          <div className="form-section p32 flx1 fc2">
            <div className="form-heading">
              <h3 className="fs36 lh34 mtb24 fw5">
                Feel free to drop us a message
              </h3>
            </div>
            <div className="form mt32">
              <form action="#" method="post">
                <div className="contact-form df fww mb16">
                  <div className="input-column df fww flx50 mb16">
                    <label className="fw5 mb8 ml84 pl4" for="">
                      Name
                    </label>
                    <input
                      className="w100 pl12 db h48 br8 brd2 mlr4"
                      type="text"
                      placeholder="Name"
                    />
                  </div>
                  <div className="input-column df fww flx50 mb16">
                    <label className="fw5 mb8 ml84 pl4" for="">
                      Email
                    </label>
                    <input
                      className=" w100 pl12 db h48 br8 brd2 mlr4"
                      type="text"
                      placeholder="Email Address"
                    />
                  </div>
                  <div className="input-column df fww flx50 mb16">
                    <label className="fw5 mb8 ml84 pl4" for="">
                      Phone
                    </label>
                    <input
                      className="w100 pl12 db h48 br8 brd2 mlr4"
                      type="text"
                      placeholder="Phone"
                    />
                  </div>
                  <div className="input-column df fww flx50 mb16">
                    <label className="fw5 mb8 ml84 pl4" for="">
                      Subject
                    </label>
                    <input
                      className="w100 pl12 db h48 br8 brd2 mlr4"
                      type="email"
                      placeholder="Subject"
                    />
                  </div>
                  <div className="df fww flx100 pr8">
                    <label className="fw5 mb8 ml84 pl4" for="">
                      Message
                    </label>
                    <textarea
                      className="flx100 pl12 pt8 mb8 db h80 br8 brd2 mlr4 "
                      name="message"
                      id=""
                      rows="7"
                      placeholder="Write a Message"
                      data-gramm="false"
                      wt-ignore-input="true"
                    ></textarea>
                  </div>
                  <div className="submit-btn h48 br8 v-center jcc plr24 mt8 cp fc1 bg2">
                    Submit Now
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </section>
      <Footer />
    </>
  );
};

export default contact;
