import React from "react";
import Head from "next/head";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Link from "next/link";
import Storage from "@/components/Storage";
import Help from "@/components/Help";

const elegant = () => {
  return (
    <>
      <Head>
        <title>Bob & Scott</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Englebert&display=swap"
          rel="stylesheet"
        />
      </Head>
      <section className="elegent-product df fww">
        <div className="elegent-product-img flx50">
          <img
            src="images/feature-img-02.webp"
            alt="feature-img-02"
            className="w100 mb12"
          />
          <img
            src="images/feature-img-06.webp"
            alt="feature-img-02"
            className="w100"
          />
        </div>
        <div className="elegent-product-content">
          <h2 className="elegent-product-content-heading heading fc2">
            Elegant Lamp
          </h2>
        </div>
      </section>
      <Header className="pa fc2" />
      <Footer />
    </>
  );
};

export default elegant;
