import React from "react";
import Head from "next/head";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Link from "next/link";
import Storage from "@/components/Storage";
import Help from "@/components/Help";

const elegant = () => {
  return (
    <>
      <Head>
        <title>Bob & Scott</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Englebert&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Header className="pa fc5 zi99" />
      <section className="elegent-product df fww bg5">
        <div className="elegent-product-img flx50">
          <img
            src="images/chair-img-01.webp"
            alt="feature-img-02"
            className="w100 mb12"
          />
          <img
            src="images/chair-img-02.webp"
            alt="feature-img-02"
            className="w100 mb12"
          />
          <img
            src="images/chair-img-03.webp"
            alt="feature-img-02"
            className="w100 df"
          />
        </div>
        <div className="product-content flx50 plr40 ptb24">
          <h2 className="product-content-heading fs80 fw5 fc2 mb24">
            MODERN CHAIR
          </h2>
          <h4 className="product-content-subheading fs18 fw5 mb24">
            $ 249.00 USD
          </h4>
          <p className="product-content-text lh24">
            Discover comfort and style in our chair section, featuring
            meticulously crafted seating solutions designed for durability and
            ergonomic support. Elevate your space with our range of quality
            chairs.
          </p>
        </div>
      </section>

      <section className="product-description  ptb72 brd-b1">
        <div className="elegent-description wrapper df fww">
          <div className="elegent-descripion-heading-text flx50">
            <h2 className="elegent-descripion-heading fs42 fc2 p24">
              Description
            </h2>
          </div>
          <div className="elegent-descripion-heading-description flx50 plr24">
            <p className="elegent-subtext lh30 taj mb24">
              Welcome to our chair section, where comfort and style converge to
              enhance your seating experience. Our curated collection features a
              range of meticulously crafted chairs designed with your utmost
              comfort in mind. From ergonomic office chairs that promote healthy
              posture during long hours of work to stylish lounge chairs that
              add flair to your living space, each piece is a testament to
              quality and durability.
            </p>
            <p className="elegent-subtext lh30 taj mb24">
              Our chairs are crafted using premium materials and innovative
              techniques, ensuring longevity and reliable performance. Whether
              you're looking for a sleek and modern design or a classic and
              timeless piece, our selection caters to diverse preferences and
              needs.
            </p>
            <p className="elegent-subtext lh30 taj mb24">
              Experience superior comfort with ergonomic features such as
              adjustable armrests, lumbar support, and breathable upholstery.
              Each chair is thoughtfully designed to provide optimal support and
              relaxation, making them ideal for both work and leisure
              environments. Elevate your space with our high-quality chairs that
              combine functionality, aesthetics, and comfort seamlessly. Find
              the perfect seating solution that complements your style and
              enhances your daily life.
            </p>
          </div>
        </div>
      </section>

      <Footer />
    </>
  );
};

export default elegant;
