import React from "react";
import Head from "next/head";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Link from "next/link";
import Storage from "@/components/Storage";
import Help from "@/components/Help";

const elegant = () => {
  return (
    <>
      <Head>
        <title>Bob & Scott</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Englebert&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Header className="fc2" />
      <section className="elegent-product df fww bg5">
        <div className="elegent-product-img flx50">
          <img
            src="images/chair-1x1-01.webp"
            alt="feature-img-02"
            className="w100 mb12"
          />
        </div>
        <div className="product-content flx1 pl24">
          <h2 className="product-content-heading fs52 fw5 fc2 mb24">
            MODERN CHAIR
          </h2>
          <h4 className="product-content-subheading fs18 fw5">$ 249.00 USD</h4>
        </div>
      </section>

      <Footer />
    </>
  );
};

export default elegant;
