import React from "react";
import Head from "next/head";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Link from "next/link";
import Help from "@/components/Help";
import { MdKeyboardArrowRight } from "react-icons/md";
import Faq from "@/components/Faq";

const faq = () => {
  return (
    <>
      <Head>
        <title>Bob & Scott - FAQs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Englebert&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Header className="pa fc2" />
      <section className="shop-hero df bg5">
        <div className="shop-hero-container wrapper df aie jcc mb24">
          <h2 className="shop-hero-container-heading inner-page-heading fc2">
            FAQs
          </h2>
        </div>
      </section>

      <div className="breadcrum ptb24 h-center">
        <ul className="breadcrum-list fc2 df fs18">
          <li className="bredcrum-item">
            <Link href="/home" className="category-item ttu plr16 v-center">
              Home <MdKeyboardArrowRight className="ml8" />
            </Link>
          </li>
          <li className="bredcrum-item">FAQs</li>
        </ul>
      </div>
      <Faq />
      <Help className="bg1" />
      <Footer />
    </>
  );
};

export default faq;
