import Header from "@/components/Header";
import Head from "next/head";
import Hero from "@/components/Hero";
import React from "react";
import Solved from "@/components/Solved";
import Featured from "@/components/Featured";
import HomeIntro from "@/components/HomeIntro";
import Room from "@/components/Room";
import Footer from "@/components/Footer";
import Help from "@/components/Help";

const home = () => {
  return (
    <>
      <Head>
        <title>Bob & Scott</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Englebert&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Header className="pa fc1" />
      <Hero />
      <HomeIntro />
      <Featured />
      <Solved />
      <Room className="bg4" />
      <Help className="bg5" />
      <Footer />
    </>
  );
};

export default home;
