import Head from "next/head";
import React from "react";
import Link from "next/link";
// import { motion } from "framer-motion";
export default function Home() {
  return (
    <>
      <Head>
        <title>Bob & Scott</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Englebert&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main>
        <section className="entrance-page bg5 df pr">
          <div className="entrance-page-container df jcc aic w100 fdc">
            <div className="logo-img zi3">
              <img src="images/logo.png" alt="logo" />
            </div>
            <Link
              href="/home"
              className="button-circle br50 transit2 tac jcc df fs20 aft pr fw6 mt12 zi3"
            >
              Enter
            </Link>
            <div className="entrance-pages-imagees ofh">
              <img
                src="images/1x1-03.webp"
                alt="1X1-IMG"
                className="image-circle pa t0 l0 mt16 ml32"
              />
              <img
                src="images/bed-1x1-01.webp"
                alt="1X1-IMG"
                className="image-circle pa b0 l0 mb16 ml32"
              />
              <img
                src="images/cabinet-1x1-01.webp"
                alt="1X1-IMG"
                className="image-circle pa t0 r0 mt32 mr40"
              />
              <img
                src="images/1x1-04.webp"
                alt="1X1-IMG"
                className="image-circle pa b0 r0 mb32 mr48"
              />
              <img
                src="images/chair-1x1-01.webp"
                alt="1X1-IMG"
                className="image-circle pa t0 mt48"
              />
              <img
                src="images/wardrobe-1x1-01.webp"
                alt="1X1-IMG"
                className="image-circle pa b0 mb48"
              />
              <img
                src="images/1x1-02.webp"
                alt="modern-chair"
                className="image-circle pa image-circle-position"
              />
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
